### ISSUE TITLE
Searching with double quotes can return unexpected results

### ISSUE THREAD

**Issue by janclarin** [janclarin/jisho-alfred-workflow#1]
According to @Kimtaro, this is due an issue with the Jisho.org API's [lack of proper support for the quotation mark feature](https://twitter.com/Kimtaro/status/842331494219575297). He should be on it [some time after April](https://twitter.com/Kimtaro/status/842331611563663361). Thank you!

e.g. [search "love" using the workflow](http://jisho.org/api/v1/search/words?keyword="love") and [search "love" on Jisho.org](http://jisho.org/search/%22love%22)

**Temporary workaround:** Search for English words without double quotations first. If romaji results appear, try surrounding with double quotations.

**Comment by Kimtaro** [comment]
@janclarin Sorry for the delay on this. I have finally fixed it. The API should now behave like the regular site for `""`-searches.

I should mention though that it's very naive, it just checks for the presence of " in the keyword, removes it and turns on `exact` mode, where I don't do any romaji<>kana conversion.

**Comment by janclarin** [comment]
@Kimtaro thank you so much! It works great. I think that method should be sufficient, I'll let you know if I encounter any bugs.
