### ISSUE TITLE
Error When Using Ji "date"

### ISSUE THREAD

**Issue by smaroukis** [janclarin/jisho-alfred-workflow#3]
Simple query returns "There was an error retrieving Jisho results". I had problems with other Alfred jisho scripts, I'm not sure if jisho updated their API. Using Alfred 2. Will post an issue with more details if I have time to dig in.

**Comment by janclarin** [comment]
I'm unable to reproduce this issue using Alfred 2 or 3 with the latest release. Please let me know what you find, thanks!

**Comment by janclarin** [comment]
Still having problems?
