### ISSUE TITLE
"Error retrieving Jisho results" in Mojave 10.14.6

### ISSUE THREAD

**Issue by ok-kenji** [janclarin/jisho-alfred-workflow#5]
Been loving this workflow, but it just recently stopped working. Queries now result in an error: "There was an issue retrieving Jisho results."

`[19:17:03.528] Logging Started...

[19:17:51.908] Jisho.org[Script Filter] Queuing argument 'hello'

[19:17:52.836] Jisho.org[Script Filter] Script with argv '(null)' finished

[19:17:52.840] STDERR: Jisho.org[Script Filter] 19:17:52 workflow.py:2225 DEBUG    Workflow version : 1.9.1

19:17:52 workflow.py:1628 DEBUG    Reading settings from `/Users/*******/Library/Application Support/Alfred/Workflow Data/com.janclarin.jisho-alfred-workflow/settings.json` ...

19:17:52 workflow.py:2514 DEBUG    Update check not due

19:17:52 workflow.py:1859 DEBUG    Loading cached data from : /Users/*******/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.janclarin.jisho-alfred-workflow/__workflow_update_status.cpickle

19:17:52 workflow.py:2444 DEBUG    update_data : {u'available': False}

19:17:52 workflow.py:2423 DEBUG    Set last run version : 1.9.1

19:17:52 workflow.py:2267 DEBUG    Workflow finished in 0.764 seconds.

[19:17:52.842] Jisho.org[Script Filter] <?xml version="1.0" encoding="utf-8"?>
<items><item valid="yes"><title>There was an issue retrieving Jisho results</title><subtitle /><arg>hello</arg><icon>/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns</icon></item></items>`

Not sure if directly related but happened soon after 10.14.6 update.

**Comment by janclarin** [comment]
Glad to hear that! As mentioned by @deanishe in [this post](https://www.alfredforum.com/topic/11871-issues-with-workflows-under-macos-1014mojave/), there are some permission issues with Mojave and workflows.

Please try following the steps outlined in: https://www.alfredapp.com/help/getting-started/permissions/

Let me know if that resolves your issue! 😄 I'm currently on 10.15.5, and the workflow still is working on Alfred 4.0.9 for me.

**Comment by ok-kenji** [comment]
Hi, thanks so much for the reply! (That was me crossposting on the Alfred forum as well. Didn't know where you'd still be active so thanks for replying to both! :D )

So I tried the steps suggested on that page, including removing and re-adding Alfred to each of the various permissions panes but alas the issue persists. I wonder if a re-install of Alfred might help? It's so odd that it works in Catalina but not Mojave.

**Comment by ok-kenji** [comment]
Just posting a followup, randomly tried it again today and it's working again. I have no explanation but am pleased. Thanks again for your input. (I'll also update the Alfred forum post)

**Comment by janclarin** [comment]
Glad to hear that it's working again! 😄
